config/routes.rb
Truthiness::Application.routes.draw do
  resources :articles

  resources :references

  resources :issues

  resources :users
  match 'login' => 'users#login'
  match 'logout' => 'users#logout'

  root :to => 'issues#index'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :description, :name, :picture, :banner_image, :heading, :summary, :splash_image
  has_many :articles
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  skip_before_filter :require_login, :only => [:index, :show]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
    @default_issue = Issue.find(1);

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :banner_image %><br />
    <%= f.text_field :banner_image %>
  </div>
  <div class="field">
    <%= f.label :heading %><br />
    <%= f.text_field :heading %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :splash_image %><br />
    <%= f.text_field :splash_image %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<!-- image comes from http://www.flickr.com/photos/chiotsrun/3241741298/sizes/l/in/photostream/ -->
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <img src="<%= @default_issue.picture %>" height="250" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1><%= @default_issue.name %></h1>
          <p class="lead"><%= @default_issue.description %></p>
          <%= link_to 'Explore', @default_issue, {class:'btn btn-large btn-primary'} %>
        </div>
      </div>
    </div>
  </div>
</div><!-- /.carousel -->


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">
  <!-- Three columns of text below the carousel -->
  <div class="row">
    <% @issues.each do |issue|
      next if issue.id == @default_issue.id
      %>
      <div class="span4">
        <img class="img-circle" width="180" height="180" src="<%= issue.picture %>">
        <h2><%= issue.name %></h2>
        <p><%= issue.description %></p>
        <p><%= link_to 'View details &raquo;'.html_safe, issue, {class:'btn'} %></p>
      </div><!-- /.span4 -->
    <% end %>
  </div><!-- /.row -->
</div><!-- /.container -->

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<div class="clearfix"></div>

<style type="text/css">
  body {
    padding-top: 20px;
    padding-bottom: 40px;
  }

  /* Custom container */
  .container-narrow {
    margin: 0 auto;
    max-width: 700px;
  }
  .container-narrow > hr {
    margin: 30px 0;
  }

  /* Main marketing message and sign up button */
  .jumbotron {
    margin: 60px 0;
    text-align: left;
  }
  .jumbotron h1 {
    font-size: 48px;
    line-height: 1;
  }
  .jumbotron .btn {
    font-size: 21px;
    padding: 14px 24px;
  }

  /* Supporting marketing content */
  .marketing {
    margin: 60px 0;
  }
  .marketing p + h4 {
    margin-top: 28px;
  }

  /* Misc overrides */
  a, a:hover {
    color: #1F8000;
  }

  .banner img {
    min-width: 100%;
    height: 300px;
  }
</style>

    <div class="container-narrow">
      <div class="masthead">
        <!-- This is a link back to the home page -->
        <h3 class="muted"><a href="/">&lt;&nbsp; More Truthiness</a></h3>
      </div>

      <div class="banner">
        <img src="<%= @issue.banner_image %>" height="250" alt="">
      </div>

      <div class="jumbotron">
        <h1><%= @issue.heading %></h1>
        <p class="lead"><%= @issue.description %></p>
      </div>

      <!-- *** get all articles associated with this issue;
           display the title and the summary here -->
      <div class="row-fluid marketing">
        <div class="span6">
          <% @issue.articles.each do |article| %>
          <h4><%= article.title.html_safe unless article.title.nil? %></h4>
          <p><%= article.summary.html_safe unless article.summary.nil? %>
             <%= link_to "Learn More", article %></p>
          <% end %>
        </div>

        <div class="span6">
          <!-- *** get image -->
          <img src="<%= @issue.splash_image %>"
               style="float: right" />
        </div>
      </div>
    </div>