config/routes.rb
Truthiness::Application.routes.draw do
  resources :articles

  resources :references

  resources :issues

  resources :users
  match 'login' => 'users#login'
  match 'logout' => 'users#logout'

  root :to => 'issues#index'

end

app/models/reference.rb
class Reference < ActiveRecord::Base
  attr_accessible :description, :article_id, :link_title, :link_url
  belongs_to :article
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  skip_before_filter :require_login, :only => [:index, :show]
  
  # GET /references
  # GET /references.json
  def index
    @references = Reference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @references }
    end
  end

  # GET /references/1
  # GET /references/1.json
  def show
    @reference = Reference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/new
  # GET /references/new.json
  def new
    @reference = Reference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/1/edit
  def edit
    @reference = Reference.find(params[:id])
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(params[:reference])

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render json: @reference, status: :created, location: @reference }
      else
        format.html { render action: "new" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /references/1
  # PUT /references/1.json
  def update
    @reference = Reference.find(params[:id])

    respond_to do |format|
      if @reference.update_attributes(params[:reference])
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference = Reference.find(params[:id])
    @reference.destroy

    respond_to do |format|
      format.html { redirect_to references_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<%= form_for(@reference) do |f| %>
  <% if @reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% @reference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue_id %><br />
    <%= f.number_field :issue_id %>
  </div>
  <div class="field">
    <%= f.label :link_title %><br />
    <%= f.text_field :link_title %>
  </div>
  <div class="field">
    <%= f.label :link_url %><br />
    <%= f.text_field :link_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editing reference</h1>

<%= render 'form' %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

app/views/references/index.html.erb
<h1>Listing references</h1>

<table>
  <tr>
    <th>Issue</th>
    <th>Link title</th>
    <th>Link url</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @references.each do |reference| %>
  <tr>
    <td><%= reference.issue_id %></td>
    <td><%= reference.link_title %></td>
    <td><%= reference.link_url %></td>
    <td><%= reference.description %></td>
    <td><%= link_to 'Show', reference %></td>
    <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
    <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reference', new_reference_path %>

app/views/references/new.html.erb
<h1>New reference</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Issue:</b>
  <%= @reference.issue_id %>
</p>

<p>
  <b>Link title:</b>
  <%= @reference.link_title %>
</p>

<p>
  <b>Link url:</b>
  <%= @reference.link_url %>
</p>

<p>
  <b>Description:</b>
  <%= @reference.description %>
</p>


<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>